version: '3.0'
services:
  app:
    # build:
    #   context: .
    #   dockerfile: ./infra/java/Dockerfile
    image: openjdk:17
    container_name: "${APP}_app"
    tty: true
    # volumes:
    # - ../${APP}/target/${APP}-0.0.1-SNAPSHOT.jar:/${APP}.jar
    volumes:
      - ../${APP}:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    # entrypoint: "java -jar /${APP}.jar"
    # ports:
    #   - 80:8080
    # ports:
    #   - '8080:8080'
    # volumes:
    #   - ../${APP}:/usr/local/src
    # entrypoint: "java -jar /usr/local/src/app.jar"
    # command: ./mvnw spring-boot:run
    # networks:
    #   - app-net
    environment:
      # APP_DIR: hoge
      # APP_DIR=${APP_DIR}
      # DB_URL: ${DB_URL}
      # DB_USERNAME: ${DB_USERNAME}
      # DB_PASSWORD: ${DB_PASSWORD}
      spring.datasource.driverClassName: ${DB_DRIVER_CLASS_NAME}
      spring.datasource.url: ${DB_URL}
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      spring.redis.host: "redis"
    depends_on:
      - db
      - redis
  db:
    build: ./infra/mysql
    container_name: "${APP}_db"
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/mysql/initdb:/docker-entrypoint-initdb.d
      - ./infra/mysql/logs:/var/log/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  # db-testing:
  #   build: ./infra/mysql
  #   container_name: "${APP}_db-testing"
  #   volumes:
  #     - db-testing-store:/var/lib/mysql
  #     - ./infra/mysql/logs:/var/log/mysql
  #   environment:
  #     - MYSQL_DATABASE=${DB_TESTING_DATABASE}
  #     - MYSQL_USER=${DB_TESTING_USERNAME}
  #     - MYSQL_PASSWORD=${DB_TESTING_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${DB_TESTING_PASSWORD}
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=${DB_TESTING_PASSWORD}
  #     - MYSQL_RANDOM_ROOT_PASSWORD=$DB_TESTING_PASSWORD}
  #     - TZ=${TZ}
  #   ports:
  #     - ${DB_TESTING_PORT}:3306
  redis:
    container_name: "${APP}_session"
    image: redis:7.0-rc1
  nginx:
    container_name: "${APP}_nginx"
    image: nginx:1.21
    restart: always
    ports:
      - 80:80
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  db-store:
    name: ${APP}_db-store
  db-testing-store:
    name: ${APP}_db-testing-store

# networks:
#   app-net:
#     driver: bridge
